language: scala
jdk:
- oraclejdk8
scala:
- 2.12.6
before_install:
- git fetch --tags
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
stages:
- name: test
jobs:
  include:
  - stage: test
    install:
    - pip install --user codecov
    script: sbt ++$TRAVIS_SCALA_VERSION validate
    after_success:
    - codecov
